/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  azsphere: [{type: 'autogenerated', dirName: 'azsphere'}],  // foldername
  everywhere: [{type: 'autogenerated', dirName: 'everywhere'}],  // foldername
  start: [{type: 'autogenerated', dirName: 'start'}],  // foldername

};

module.exports = sidebars;
